#!/bin/sh
# `/sbin/setuser memcache` runs the given command as the user `memcache`.
# If you omit that part, the command will be run as root.
#exec /sbin/setuser memcache /usr/bin/memcached >>/var/log/memcached.log 2>&1
# TODO: Don't run as root.
export PORT=5000
exec node /opt/services/pinf-to-docker/server.js >> /var/log/pinf-to-docker.log 2>&1
